--generations
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (00,0,'N/A');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (01,0,'I');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (02,0,'II');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (03,0,'III');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (04,0,'IV');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (05,0,'V');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (06,0,'VI');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (07,0,'VII');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (08,0,'VIII');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (09,0,'IX');
INSERT INTO generations (GENID,TABLENUMBER,GENNAME) VALUES (10,0,'X');
--elemtypes
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01090,01,09,'N/A');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01091,01,09,'Normal');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01092,01,09,'Fighting');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01093,01,09,'Flying');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01094,01,09,'Poison');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01095,01,09,'Ground');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01096,01,09,'Rock');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01097,01,09,'Bug');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01098,01,09,'Ghost');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (01099,01,09,'Steel');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010910,01,09,'Fire');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010911,01,09,'Water');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010912,01,09,'Grass');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010913,01,09,'Electric');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010914,01,09,'Psychic');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010915,01,09,'Ice');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010916,01,09,'Dragon');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010917,01,09,'Dark');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010918,01,09,'Fairy');
INSERT INTO elemtypes (ELEMTYPEID,TABLENUMBER,GENID,ELEMTYPENAME) VALUES (010919,01,09,'Stellar');
--abilities
